export const dummyRestaurantData = [
  {
    id: 1,
    cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
    name: "Ristorante Italiano",
    avgRating: 4.2,
    cuisines: ["Italian"],
    areaName: "Kondhwa",
  },
  {
    id: 2,
    cloudinaryImageId: "gsjdnjaohsvbbp0uspfz",
    name: "Taco Town",
    avgRating: 4.0,
    cuisines: ["Mexican"],
    areaName: "Viman Nagar",
  },
  {
    id: 3,
    cloudinaryImageId: "byilgyrcfz690ryoasww",
    name: "Sushi Sensation",
    avgRating: 4.8,
    cuisines: ["Japanese", "Sushi"],
    areaName: "Pimpri",
  },
  {
    id: 4,
    cloudinaryImageId: "f01666ac73626461d7455d9c24005cd4",
    name: "Burger Bistro",
    avgRating: 4.5,
    cuisines: ["American", "Burgers"],
    areaName: "Kondhwa",
  },
  {
    id: 5,
    cloudinaryImageId: "b2edbc28b7b8219d6e0a9c049ce06658",
    name: "La Pizzeria",
    avgRating: 4.3,
    cuisines: ["Italian", "Pizza"],
    areaName: "Viman Nagar",
  },
  {
    id: 6,
    cloudinaryImageId: "2b4f62d606d1b2bfba9ba9e5386fabb7",
    name: "Chez Pierre",
    avgRating: 4.7,
    cuisines: ["French"],
    areaName: "Pimpri",
  },
  {
    id: 7,
    cloudinaryImageId: "byilgyrcfz690ryoasww",
    name: "Curry Corner",
    avgRating: 4.1,
    cuisines: ["Indian"],
    areaName: "Kondhwa",
  },
  {
    id: 8,
    cloudinaryImageId: "b2edbc28b7b8219d6e0a9c049ce06658",
    name: "Thai Terrace",
    avgRating: 4.6,
    cuisines: ["Thai"],
    areaName: "Viman Nagar",
  },
  {
    id: 9,
    cloudinaryImageId: "f01666ac73626461d7455d9c24005cd4",
    name: "Steakhouse Supreme",
    avgRating: 4.9,
    cuisines: ["Steakhouse", "American"],
    areaName: "Pimpri",
  },
  {
    id: 10,
    cloudinaryImageId: "gsjdnjaohsvbbp0uspfz",
    name: "Mediterranean Magic",
    avgRating: 4.4,
    cuisines: ["Mediterranean"],
    areaName: "Kondhwa",
  },
];
